# Generated by Django 4.2.7 on 2023-12-03 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='activo',
        ),
    ]
